name: assistant_entretien_chaudiere
description: Assistant pour l'entretien de chaudiÃ¨re
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0