name: assistant_entreiten_chaudiere
description: Assistant pour l'entretien de chaudiÃ¨re

publish_to: 'none'

version: 1.1.0+28

environment:
  sdk: '>=3.0.0 <4.0.0'

  flutter: ">=3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.0
  provider: ^6.1.1
  flutter_riverpod: ^3.2.1
  material_design_icons_flutter: ^7.0.7296
  uuid: ^4.5.1
  
  # Graphiques
  fl_chart: ^1.1.1
  share_plus: ^12.0.1
#   vibration: ^1.8.4
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  http: ^1.1.2
  image: ^4.1.7
  intl: ^0.17.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.2
  pdf: ^3.10.7
  flutter_ringtone_player: ^4.0.0+2
  charts_flutter_new: ^0.12.0
  printing: ^5.11.0
  in_app_update: ^4.2.0
  image_picker: ^1.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/qualigaz_codes.json
    - lib/data/reglementation_questions.json
